Repository AY2021S1-CS2103T-T11-3/tp, pull requests merged in 2020-10, with the labels that each got.

#37 Add jackson storage support for finance records and inventory records
  src/main/java/nustorage/storage/JsonAdaptedFinanceRecord.java
  src/main/java/nustorage/storage/JsonAdaptedInventoryRecord.java
  src/test/java/nustorage/logic/commands/CommandTestUtil.java
  src/test/java/nustorage/storage/JsonAdaptedFinanceRecordTest.java
  src/test/java/nustorage/storage/JsonAdaptedInventoryRecordTest.java
  src/test/java/nustorage/testutil/TypicalFinanceRecords.java
  src/test/java/nustorage/testutil/TypicalInventoryRecords.java
Labels: priority.Medium

#42 Linked add-inventory with add-finance
  src/main/java/nustorage/logic/commands/AddInventoryCommand.java
  src/main/java/nustorage/logic/parser/AddInventoryCommandParser.java
  src/main/java/nustorage/logic/parser/CliSyntax.java
  src/main/java/nustorage/logic/parser/ParserUtil.java
  src/main/java/nustorage/model/record/FinanceRecord.java
  src/main/java/nustorage/storage/JsonAdaptedFinanceRecord.java
  src/test/java/nustorage/logic/commands/CommandTestUtil.java
  src/test/java/nustorage/storage/JsonAdaptedFinanceRecordTest.java
Labels: priority.Medium

#41 List finance records
  src/main/java/nustorage/logic/commands/ListFinanceRecordsCommand.java
  src/main/java/nustorage/logic/parser/AddressBookParser.java
  src/main/java/nustorage/model/FinanceAccount.java
  src/main/java/nustorage/model/Model.java
  src/main/java/nustorage/model/ModelManager.java
  src/test/java/nustorage/logic/commands/AddCommandTest.java
Labels: priority.High

#44 List Inventory
  docs/AboutUs.md
  docs/DeveloperGuide.md
  src/main/java/nustorage/logic/Logic.java
  src/main/java/nustorage/logic/LogicManager.java
  src/main/java/nustorage/logic/commands/AddInventoryCommand.java
  src/main/java/nustorage/logic/commands/CommandResult.java
  src/main/java/nustorage/logic/commands/ListInventoryCommand.java
  src/main/java/nustorage/logic/parser/AddressBookParser.java
  src/main/java/nustorage/model/Model.java
  src/main/java/nustorage/model/ModelManager.java
  src/main/java/nustorage/model/item/Inventory.java
  src/main/java/nustorage/model/item/ReadOnlyInventory.java
  src/main/java/nustorage/ui/InventoryPanel.java
  src/main/java/nustorage/ui/InventoryRecordCard.java
  src/main/java/nustorage/ui/MainWindow.java
  src/main/java/nustorage/ui/UiManager.java
  src/main/resources/view/InventoryCard.fxml
  src/main/resources/view/InventoryPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/nustorage/logic/commands/AddCommandTest.java
Labels: priority.High

#47 Fix CI and add list_inventory
  src/main/java/nustorage/logic/commands/ListInventoryCommand.java
  src/main/java/nustorage/logic/parser/AddressBookParser.java
Labels: priority.High

#51 Update optional field for add-inventory
  src/main/java/nustorage/logic/commands/AddInventoryCommand.java
  src/main/java/nustorage/logic/parser/AddInventoryCommandParser.java
Labels: priority.Medium

#54 Add codecov badge to readme
  README.md
Labels: priority.Medium

#55 Refactor Inventory class
  src/main/java/nustorage/model/Inventory.java
  src/main/java/nustorage/model/ModelManager.java
  src/main/java/nustorage/model/ReadOnlyInventory.java
  src/main/java/nustorage/model/record/InventoryRecord.java
  src/main/java/nustorage/model/record/exceptions/NegativeNumberOfItemException.java
Labels: priority.Low

#56 Prepare finance class for FXML display
  src/main/java/nustorage/logic/commands/AddFinanceCommand.java
  src/main/java/nustorage/logic/commands/EditFinanceCommand.java
  src/main/java/nustorage/logic/commands/ListFinanceRecordsCommand.java
  src/main/java/nustorage/model/FinanceAccount.java
  src/main/java/nustorage/model/Model.java
  src/main/java/nustorage/model/ModelManager.java
  src/main/java/nustorage/model/record/FinanceRecord.java
  src/main/java/nustorage/storage/JsonAdaptedFinanceRecord.java
  src/test/java/nustorage/logic/commands/AddCommandTest.java
Labels: priority.High

#57 Implement edit finance
  src/main/java/nustorage/logic/commands/EditFinanceCommand.java
  src/main/java/nustorage/logic/parser/AddressBookParser.java
  src/main/java/nustorage/logic/parser/EditFinanceCommandParser.java
Labels: priority.High

#59 V1.2 delete inventory
  src/main/java/nustorage/logic/commands/AddInventoryRecordCommand.java
  src/main/java/nustorage/logic/commands/DeleteInventoryRecordCommand.java
  src/main/java/nustorage/logic/parser/AddInventoryRecordCommandParser.java
  src/main/java/nustorage/logic/parser/AddressBookParser.java
  src/main/java/nustorage/logic/parser/DeleteInventoryRecordCommandParser.java
  src/main/java/nustorage/model/Model.java
  src/main/java/nustorage/model/ModelManager.java
  src/test/java/nustorage/logic/commands/AddCommandTest.java
Labels: priority.High, type.Enhancement

#53 Add storage support
  src/main/java/nustorage/MainApp.java
  src/main/java/nustorage/logic/LogicManager.java
  src/main/java/nustorage/model/FinanceAccount.java
  src/main/java/nustorage/model/Model.java
  src/main/java/nustorage/model/ModelManager.java
  src/main/java/nustorage/model/UserPrefs.java
  src/main/java/nustorage/storage/FinanceAccountStorage.java
  src/main/java/nustorage/storage/InventoryStorage.java
  src/main/java/nustorage/storage/JsonFinanceAccountStorage.java
  src/main/java/nustorage/storage/JsonInventoryStorage.java
  src/main/java/nustorage/storage/JsonSerializableFinanceAccount.java
  src/main/java/nustorage/storage/JsonSerializableInventory.java
  src/main/java/nustorage/storage/Storage.java
  src/main/java/nustorage/storage/StorageManager.java
  src/test/java/nustorage/logic/LogicManagerTest.java
  src/test/java/nustorage/logic/commands/AddCommandTest.java
  src/test/java/nustorage/storage/StorageManagerTest.java
Labels: priority.High, type.Task

#62 Refactor method names to compile
  src/main/java/nustorage/model/FinanceAccount.java
  src/main/java/nustorage/storage/FinanceAccountStorage.java
  src/main/java/nustorage/storage/JsonAddressBookStorage.java
  src/main/java/nustorage/storage/JsonFinanceAccountStorage.java
  src/main/java/nustorage/storage/JsonSerializableFinanceAccount.java
  src/main/java/nustorage/storage/Storage.java
  src/main/java/nustorage/storage/StorageManager.java
Labels: severity.High

#67 Update UserGuide and Error messages for Inventory
  docs/UserGuide.md
  src/main/java/nustorage/logic/commands/AddInventoryRecordCommand.java
  src/main/resources/view/MainWindow.fxml
Labels: priority.Medium

#69 Update UserGuide
  docs/UserGuide.md
Labels: priority.Medium

#71 Storage: fix loading from json file resolves #65
  .gitignore
  preferences.json
  src/main/java/nustorage/MainApp.java
  src/main/java/nustorage/logic/commands/AddFinanceCommand.java
  src/main/java/nustorage/logic/commands/exceptions/CommandException.java
  src/main/java/nustorage/model/FinanceAccount.java
  src/main/java/nustorage/model/Model.java
  src/main/java/nustorage/model/ModelManager.java
  src/main/java/nustorage/model/ReadOnlyFinanceAccount.java
  src/main/java/nustorage/model/record/FinanceRecordList.java
  src/main/java/nustorage/storage/FinanceAccountStorage.java
  src/main/java/nustorage/storage/JsonAdaptedFinanceRecord.java
  src/main/java/nustorage/storage/JsonAdaptedInventoryRecord.java
  src/main/java/nustorage/storage/JsonAddressBookStorage.java
  src/main/java/nustorage/storage/JsonFinanceAccountStorage.java
  src/main/java/nustorage/storage/JsonInventoryStorage.java
  src/main/java/nustorage/storage/JsonSerializableFinanceAccount.java
  src/main/java/nustorage/storage/JsonSerializableInventory.java
  src/main/java/nustorage/storage/Storage.java
  src/main/java/nustorage/storage/StorageManager.java
  src/test/java/nustorage/logic/commands/AddCommandTest.java
  src/test/java/nustorage/logic/commands/AddFinanceCommandTest.java
  src/test/java/nustorage/testutil/FinanceRecordBuilder.java
  src/test/java/nustorage/testutil/TypicalFinanceRecords.java
  src/test/java/nustorage/testutil/stub/ModelStub.java
Labels: priority.High

#72 Finish storage functionality, resolves #15 #65
  .gitignore
  preferences.json
  src/main/java/nustorage/MainApp.java
  src/main/java/nustorage/logic/LogicManager.java
  src/main/java/nustorage/logic/commands/exceptions/CommandException.java
  src/main/java/nustorage/model/FinanceAccount.java
  src/main/java/nustorage/model/Model.java
  src/main/java/nustorage/model/ModelManager.java
  src/main/java/nustorage/model/ReadOnlyFinanceAccount.java
  src/main/java/nustorage/model/UserPrefs.java
  src/main/java/nustorage/storage/FinanceAccountStorage.java
  src/main/java/nustorage/storage/InventoryStorage.java
  src/main/java/nustorage/storage/JsonAdaptedFinanceRecord.java
  src/main/java/nustorage/storage/JsonAdaptedInventoryRecord.java
  src/main/java/nustorage/storage/JsonFinanceAccountStorage.java
  src/main/java/nustorage/storage/JsonInventoryStorage.java
  src/main/java/nustorage/storage/JsonSerializableFinanceAccount.java
  src/main/java/nustorage/storage/JsonSerializableInventory.java
  src/main/java/nustorage/storage/Storage.java
  src/main/java/nustorage/storage/StorageManager.java
  src/test/java/nustorage/logic/LogicManagerTest.java
  src/test/java/nustorage/logic/commands/AddCommandTest.java
  src/test/java/nustorage/storage/StorageManagerTest.java
  src/test/java/nustorage/testutil/stub/ModelStub.java
Labels: priority.Urgent

#70 Update UserGuide
  docs/UserGuide.md
Labels: priority.Medium

#79 Updated DG logic section
  docs/DeveloperGuide.md
  docs/images/DeleteFinanceSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/Ui.png
  docs/index.md
  src/main/java/nustorage/logic/LogicManager.java
  src/main/java/nustorage/logic/parser/NuStorageParser.java
  src/test/java/nustorage/logic/parser/NuStorageParserTest.java
Labels: type.Documentation

#82 Update UserGuide.md and DeveloperGuide.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/ModelClassDiagram.jpg
  docs/images/ModelClassDiagram.png
  docs/images/NUStorage.png
Labels: type.Documentation, type.Enhancement

#81 Update DG storage
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/images/AboutUs/damithc.png
  docs/images/AboutUs/door-oof.png
  docs/images/AboutUs/elgoh.png
  docs/images/AboutUs/eugeneteu.png
  docs/images/AboutUs/fizzyagent.png
  docs/images/AboutUs/howtoosee.png
  docs/images/AboutUs/ironbiscuit.png
  docs/images/BetterModelClassDiagram.png
  docs/images/LoadFinanceSequenceDiagram.png
  docs/images/LoadingFinanceActivityDiagram.png
  docs/images/LogicStorageDIP.png
  docs/images/SaveInventorySequenceDiagram.png
  docs/images/SavingInventoryActivityDiagram.png
  docs/images/SeEduLogo.png
  docs/images/StorageClassDiagram.png
  docs/images/findAlexDavidResult.png
  docs/images/helpMessage.png
  docs/images/johndoe.png
  docs/images/request_access.png
Labels: priority.Medium, type.Documentation

#83 Update header of UserGuide.md and index.md
  docs/UserGuide.md
  docs/index.md
Labels: type.Documentation

#92 Add financeID to inventory
  src/main/java/nustorage/model/record/InventoryRecord.java
Labels: priority.High

#93 Add finance record hashmap
  build.gradle
  src/main/java/nustorage/logic/commands/AddInventoryRecordCommand.java
  src/main/java/nustorage/model/FinanceAccount.java
  src/main/java/nustorage/model/ModelManager.java
  src/main/java/nustorage/model/record/InventoryRecord.java
Labels: priority.Medium

#96 Make storage take in ReadOnlyInventory
  src/main/java/nustorage/MainApp.java
  src/main/java/nustorage/model/Inventory.java
  src/main/java/nustorage/model/ModelManager.java
  src/main/java/nustorage/storage/InventoryStorage.java
  src/main/java/nustorage/storage/JsonFinanceAccountStorage.java
  src/main/java/nustorage/storage/JsonInventoryStorage.java
  src/main/java/nustorage/storage/Storage.java
  src/main/java/nustorage/storage/StorageManager.java
Labels: priority.High

#99 Refactor Inventory class
  src/main/java/nustorage/model/Inventory.java
  src/main/java/nustorage/model/ModelManager.java
  src/main/java/nustorage/model/ReadOnlyInventory.java
  src/main/java/nustorage/model/record/InventoryRecord.java
  src/main/java/nustorage/model/record/InventoryRecordList.java
  src/main/java/nustorage/storage/JsonSerializableInventory.java
Labels: priority.Medium, type.Documentation

#101 Edit UserGuide
  docs/UserGuide.md
Labels: type.Documentation

#102 Add find_inventory command
  src/main/java/nustorage/commons/core/Messages.java
  src/main/java/nustorage/logic/commands/FindInventoryRecordCommand.java
  src/main/java/nustorage/logic/commands/ListInventoryCommand.java
  src/main/java/nustorage/logic/parser/FindInventoryRecordCommandParser.java
  src/main/java/nustorage/logic/parser/NuStorageParser.java
  src/main/java/nustorage/model/record/InventoryRecordNameContainsKeywordsPredicate.java
  src/main/java/nustorage/ui/MainWindow.java
  src/main/java/nustorage/ui/uilogic/UiLogicManager.java
Labels: priority.High, type.Documentation, type.Enhancement

#108 Update UGDG closes #78
  .gitignore
  docs/DeveloperGuide.md
  docs/DeveloperGuide_ProposedFeatures.md
  docs/images/AddInventoryCommandExecuteSequenceDiagram.png
  docs/images/AddInventoryRecordSequenceDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteFinanceSequenceDiagram.png
  docs/images/DeleteInventoryRecordCommandExecuteSequenceDiagram.png
  docs/images/DeleteInventoryRecordSequenceDiagram.png
  docs/images/EditFinanceCommandExecuteSequenceDiagram.png
  docs/images/EditFinanceSequenceDiagram.png
  docs/images/InventoryUI.png
  docs/images/ListCommandExecuteSequence.png
  docs/images/ListInventorySequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ReadFinanceSequenceDiagram.png
  docs/images/SaveInventorySequenceDiagram.png
Labels: priority.Medium

#109 Change header case
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.Medium

#110 Add assertions to storage
  src/main/java/nustorage/storage/JsonAdaptedFinanceRecord.java
  src/main/java/nustorage/storage/JsonAdaptedInventoryRecord.java
  src/main/java/nustorage/storage/JsonFinanceAccountStorage.java
  src/main/java/nustorage/storage/JsonInventoryStorage.java
  src/main/java/nustorage/storage/JsonSerializableFinanceAccount.java
  src/main/java/nustorage/storage/JsonSerializableInventory.java
Labels: priority.Medium

#111 Fix UG problem
  docs/UserGuide.md
Labels: type.Documentation

#113 Update class diagram of Model class
  docs/images/ModelClassDiagram.png
Labels: type.Documentation

#117 V1.3 add test cases for Inventory class
  src/main/java/nustorage/model/record/InventoryRecordList.java
  src/main/java/nustorage/model/record/exceptions/DuplicateInventoryRecordException.java
  src/main/java/nustorage/model/record/exceptions/InventoryRecordNotFoundException.java
  src/test/java/nustorage/model/InventoryTest.java
  src/test/java/nustorage/testutil/InventoryRecordBuilder.java
Labels: priority.Medium, type.Documentation

#118 Implement find finance
  src/main/java/nustorage/commons/core/Messages.java
  src/main/java/nustorage/logic/commands/AddFinanceCommand.java
  src/main/java/nustorage/logic/commands/DeleteFinanceCommand.java
  src/main/java/nustorage/logic/commands/FindFinanceCommand.java
  src/main/java/nustorage/logic/parser/CliSyntax.java
  src/main/java/nustorage/logic/parser/FindFinanceCommandParser.java
  src/main/java/nustorage/logic/parser/NuStorageParser.java
  src/main/java/nustorage/model/FinanceAccount.java
  src/main/java/nustorage/model/Model.java
  src/main/java/nustorage/model/ModelManager.java
  src/main/java/nustorage/model/record/FinanceRecord.java
  src/main/java/nustorage/model/record/FinanceRecordList.java
  src/main/java/nustorage/model/record/exceptions/DuplicateFinanceRecordException.java
  src/main/java/nustorage/model/record/exceptions/FinanceRecordNotFoundException.java
  src/test/java/nustorage/logic/commands/AddCommandTest.java
  src/test/java/nustorage/testutil/stub/ModelStub.java
Labels: priority.High, type.Story

#119 Update logic class diagram
  docs/images/LogicClassDiagram.png
Labels: type.Documentation

#120 Improve UI
  src/main/java/nustorage/model/record/FinanceRecord.java
  src/main/java/nustorage/model/record/InventoryRecord.java
  src/main/java/nustorage/ui/Finance.java
  src/main/java/nustorage/ui/FinanceRecordCard.java
  src/main/java/nustorage/ui/FinanceRecordPanel.java
  src/main/java/nustorage/ui/Inventory.java
  src/main/java/nustorage/ui/InventoryPanel.java
  src/main/java/nustorage/ui/InventoryRecordCard.java
  src/main/java/nustorage/ui/MainWindow.java
  src/main/java/nustorage/ui/UiManager.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Finance.fxml
  src/main/resources/view/FinanceListCard.fxml
  src/main/resources/view/FinanceListPanel.fxml
  src/main/resources/view/Inventory.fxml
  src/main/resources/view/InventoryCard.fxml
  src/main/resources/view/InventoryPanel.fxml
  src/main/resources/view/MainWindow.fxml
Labels: priority.Medium, type.Enhancement

#122 Update AddInventoryRecordCommand to prevent duplicates in the Inventory
  src/main/java/nustorage/logic/commands/AddInventoryRecordCommand.java
Labels: priority.Urgent, type.Bug

#123 Update storage to link finance record to corresponding inventory record
  src/main/java/nustorage/logic/commands/EditFinanceCommand.java
  src/main/java/nustorage/logic/commands/FindFinanceCommand.java
  src/main/java/nustorage/model/record/FinanceRecord.java
  src/main/java/nustorage/model/record/InventoryRecord.java
  src/main/java/nustorage/storage/JsonAdaptedFinanceRecord.java
  src/main/java/nustorage/storage/JsonAdaptedInventoryRecord.java
  src/main/java/nustorage/ui/Finance.java
  src/main/java/nustorage/ui/Inventory.java
  src/test/java/nustorage/storage/JsonAdaptedInventoryRecordTest.java
  src/test/java/nustorage/testutil/FinanceRecordBuilder.java
  src/test/java/nustorage/testutil/TypicalInventoryRecords.java
Labels: priority.High

#124 Touch up UG
  docs/UserGuide.md
Labels: priority.Low

#125 Remove bullet points in TOC
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_config.yml
  docs/_sass/minima/_layout.scss
Labels: priority.Low

#130 Update website styling
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.Low

#132 Branch remove ab3
  src/main/java/nustorage/logic/commands/ListFinanceRecordsCommand.java
  src/main/java/nustorage/logic/commands/ListInventoryCommand.java
  src/main/java/nustorage/model/Model.java
  src/main/java/nustorage/model/ModelManager.java
  src/test/java/nustorage/logic/commands/AddInventoryCommandTest.java
  src/test/java/nustorage/logic/commands/CommandTestUtil.java
  src/test/java/nustorage/logic/parser/EditFinanceCommandParserTest.java
  src/test/java/nustorage/testutil/stub/ModelStub.java
Labels: priority.High

#134 Update ugdg
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Documentation

#135 Add tests for storage
  src/main/java/nustorage/storage/JsonFinanceAccountStorage.java
  src/main/java/nustorage/storage/JsonInventoryStorage.java
  src/test/data/JsonFinanceAccountStorageTest/financeAccount.json
  src/test/data/JsonFinanceAccountStorageTest/invalidFinanceAccount.json
  src/test/data/JsonFinanceAccountStorageTest/invalidRecord.json
  src/test/data/JsonFinanceAccountStorageTest/inventory.json
  src/test/data/JsonInventoryStorageTest/financeAccount.json
  src/test/data/JsonInventoryStorageTest/invalidInventory.json
  src/test/data/JsonInventoryStorageTest/invalidInventory2.json
  src/test/data/JsonInventoryStorageTest/invalidRecord.json
  src/test/data/JsonInventoryStorageTest/inventory.json
  src/test/java/nustorage/storage/JsonFinanceAccountStorageTest.java
  src/test/java/nustorage/storage/JsonInventoryStorageTest.java
  src/test/java/nustorage/storage/JsonUserPrefsStorageTest.java
Labels: priority.High

#138 Fix bug: ui not reading datetime from finance
  src/main/java/nustorage/ui/Finance.java
Labels: severity.High, type.Bug

#141 Update UG find finance
  docs/UserGuide.md
Labels: type.Documentation

#143 V1.3 create inventory
  src/main/java/nustorage/logic/commands/CreateInventoryRecordCommand.java
  src/main/java/nustorage/logic/commands/EditInventoryCommand.java
  src/main/java/nustorage/logic/parser/CreateInventoryRecordCommandParser.java
  src/main/java/nustorage/logic/parser/EditInventoryCommandParser.java
  src/main/java/nustorage/logic/parser/NuStorageParser.java
  src/test/java/nustorage/logic/commands/CreateInventoryCommandTest.java
Labels: priority.High, type.Enhancement

#149 V1.3 Edit inventory update
  src/main/java/nustorage/logic/commands/EditInventoryCommand.java
  src/main/java/nustorage/logic/commands/UpdateInventoryCommand.java
  src/main/java/nustorage/logic/parser/CliSyntax.java
  src/main/java/nustorage/logic/parser/CreateInventoryRecordCommandParser.java
  src/main/java/nustorage/logic/parser/EditInventoryCommandParser.java
  src/main/java/nustorage/model/record/FinanceRecord.java
  src/main/java/nustorage/model/record/InventoryRecord.java
  src/main/java/nustorage/storage/JsonAdaptedInventoryRecord.java
  src/test/data/JsonInventoryStorageTest/invalidInventory.json
  src/test/data/JsonInventoryStorageTest/invalidInventory2.json
  src/test/data/JsonInventoryStorageTest/inventory.json
  src/test/java/nustorage/logic/commands/CommandTestUtil.java
  src/test/java/nustorage/storage/JsonAdaptedInventoryRecordTest.java
  src/test/java/nustorage/testutil/InventoryRecordBuilder.java
  src/test/java/nustorage/testutil/TypicalInventoryRecords.java
Labels: priority.High, type.Documentation

#152 V1.3 Minor changes in UserGuide
  docs/UserGuide.md
  src/main/java/nustorage/logic/parser/CreateInventoryRecordCommandParser.java
  src/main/java/nustorage/model/record/FinanceRecord.java
  src/main/java/nustorage/model/record/InventoryRecord.java
  src/main/java/nustorage/ui/InventoryWindow.java
Labels: type.Enhancement

#156 V1.3 user guide update
  docs/UserGuide.md
  docs/images/commands/create_inventory_command.png
  docs/images/commands/create_inventory_finance_record_result.png
  docs/images/commands/create_inventory_result.png
  docs/images/commands/delete_finance_from_inventory_result.png
  docs/images/commands/delete_inventory_command.png
  docs/images/commands/delete_inventory_result.png
  docs/images/commands/edit_inventory_command.png
  docs/images/commands/edit_inventory_finance_result.png
  docs/images/commands/edit_inventory_result.png
  docs/images/commands/find_inventory_command.png
  docs/images/commands/find_inventory_result.png
  docs/images/commands/list_inventory_command.png
  docs/images/commands/list_inventory_result.png
  docs/images/commands/update_inventory_command.png
  docs/images/commands/update_inventory_finance_result.png
  docs/images/commands/update_inventory_result.png
  src/main/java/nustorage/commons/core/Messages.java
  src/main/java/nustorage/logic/commands/CreateInventoryRecordCommand.java
  src/main/java/nustorage/logic/commands/DeleteInventoryRecordCommand.java
  src/main/java/nustorage/logic/commands/EditFinanceCommand.java
  src/main/java/nustorage/logic/commands/EditInventoryCommand.java
  src/main/java/nustorage/logic/commands/ListInventoryCommand.java
  src/main/java/nustorage/logic/commands/UpdateInventoryCommand.java
  src/main/java/nustorage/logic/parser/EditFinanceCommandParser.java
  src/main/java/nustorage/logic/parser/ParserUtil.java
  src/main/java/nustorage/model/record/InventoryRecord.java
  src/test/java/nustorage/logic/parser/EditFinanceCommandParserTest.java
Labels: type.Bug, type.Documentation, type.Story

#158 Update EditFinanceCommand.java
  src/main/java/nustorage/logic/commands/EditFinanceCommand.java
Labels: priority.Medium, type.Documentation
