Repository AY2021S1-CS2103T-T11-3/tp, pull requests merged in 2020-11, with the labels that each got.

#200 Fix quick start section closes #189
  docs/UserGuide.md
Labels: severity.Medium, type.Documentation

#201 Update UG
  docs/UserGuide.md
Labels: type.Documentation

#202 Fix update_inventory command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/nustorage/logic/commands/UpdateInventoryCommand.java
  src/main/java/nustorage/logic/parser/EditInventoryCommandParser.java
Labels: priority.Urgent, severity.High

#205 Fix negative values acceptance in edit_inventory and create_inventory
  src/main/java/nustorage/logic/commands/CreateInventoryRecordCommand.java
  src/main/java/nustorage/logic/commands/EditInventoryCommand.java
  src/main/java/nustorage/logic/parser/CreateInventoryRecordCommandParser.java
  src/main/java/nustorage/logic/parser/EditInventoryCommandParser.java
  src/main/java/nustorage/ui/MainWindow.java
Labels: priority.High

#204 V1.4 bug fix
  src/main/java/nustorage/logic/commands/EditInventoryCommand.java
  src/main/java/nustorage/logic/parser/EditInventoryCommandParser.java
  src/main/java/nustorage/logic/parser/NuStorageParser.java
Labels: priority.High, severity.High, type.Bug

#206 V1.4 bug fix
  src/main/java/nustorage/commons/util/StringUtil.java
  src/test/java/nustorage/commons/util/StringUtilTest.java
Labels: priority.Medium, type.Enhancement

#210 V1.4 bug fix
  src/main/java/nustorage/logic/commands/CreateInventoryRecordCommand.java
  src/main/java/nustorage/logic/commands/EditInventoryCommand.java
  src/main/java/nustorage/logic/parser/CreateInventoryRecordCommandParser.java
  src/main/java/nustorage/logic/parser/EditInventoryCommandParser.java
Labels: priority.Medium

#215 Update UG website
  docs/UserGuide.md
  docs/images/commands/clear_command_finance.jpg
  docs/images/commands/clear_command_inventory.jpg
  docs/images/commands/clear_command_result_finance.jpg
  docs/images/commands/clear_command_result_inventory.jpg
  docs/images/commands/goto_finance_command.png
  docs/images/commands/goto_finance_result.png
  docs/images/commands/goto_inventory_command.png
  docs/images/commands/goto_inventory_result.png
  docs/images/commands/help_command.jpg
  docs/images/commands/help_command_result.jpg
  docs/images/commands/switch_command_finance_start.jpg
  docs/images/commands/switch_command_finance_toinventory.jpg
  docs/images/commands/switch_command_inventory_start.jpg
  docs/images/commands/switch_command_inventory_tofinance.jpg
Labels: priority.Medium, type.Documentation

#217 Update AboutUs and PPP
  docs/AboutUs.md
  docs/team/howtoosee.md
  docs/team/xihao.md
Labels: type.Documentation

#219 Update PPP links
  docs/AboutUs.md
  docs/team/elgoh.md
  docs/team/ironbiscuit.md
Labels: type.Documentation

#224 V1.4 bug prevention
  src/main/java/nustorage/logic/commands/CreateInventoryRecordCommand.java
  src/main/java/nustorage/logic/parser/CreateInventoryRecordCommandParser.java
  src/main/java/nustorage/logic/parser/EditInventoryCommandParser.java
  src/main/java/nustorage/logic/parser/ParserUtil.java
  src/test/java/nustorage/logic/commands/CommandTestUtil.java
  src/test/java/nustorage/logic/commands/CreateInventoryCommandTest.java
  src/test/java/nustorage/logic/commands/EditInventoryCommandTest.java
  src/test/java/nustorage/logic/parser/CreateInventoryRecordCommandParserTest.java
  src/test/java/nustorage/logic/parser/EditInventoryCommandParserTest.java
  src/test/java/nustorage/testutil/InventoryRecordBuilder.java
  src/test/java/nustorage/testutil/TypicalFinanceRecords.java
Labels: priority.High, type.Documentation

#228 Edit DG
  docs/DeveloperGuide.md
Labels: type.Documentation

#236 V1.4 bug prevention
  docs/team/elgoh.md
  src/main/java/nustorage/commons/core/Messages.java
  src/main/java/nustorage/logic/commands/EditInventoryCommand.java
  src/main/java/nustorage/logic/parser/EditInventoryCommandParser.java
  src/main/java/nustorage/logic/parser/ParserUtil.java
  src/test/java/nustorage/logic/commands/CommandTestUtil.java
  src/test/java/nustorage/logic/commands/EditInventoryCommandTest.java
  src/test/java/nustorage/logic/parser/EditInventoryCommandParserTest.java
  src/test/java/nustorage/testutil/InventoryRecordBuilder.java
Labels: priority.Medium, type.Documentation

#239 Update edit and create inventory classes to limit cost and quantity
  src/main/java/nustorage/logic/commands/EditInventoryCommand.java
  src/main/java/nustorage/logic/parser/CreateInventoryRecordCommandParser.java
  src/main/java/nustorage/logic/parser/EditInventoryCommandParser.java
  src/main/java/nustorage/logic/parser/ParserUtil.java
Labels: priority.Medium, type.Documentation

#244 V1.4 ugdg
  docs/UserGuide.md
Labels: priority.Medium, type.Documentation

#249 V1.4 ugdg
  docs/DeveloperGuide.md
  docs/diagrams/logic/AddInventoryCommandExecuteSequenceDiagram.xml
  docs/images/AddInventoryCommandExecuteSequenceDiagram.png
  docs/images/AddInventoryRecordSequenceDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteInventoryRecordCommandExecuteSequenceDiagram.png
  docs/images/DeleteInventoryRecordSequenceDiagram.png
  docs/images/FindInventoryRecordSequenceDiagram.png
  docs/team/elgoh.md
Labels: priority.Medium, type.Documentation
